apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-nssf-config
  namespace: smallcell-p5g
  labels:
    ngc-mode: nssf
data:
  nssf.yaml: |
    logger:
      level: trace

    nssf:
      sbi:
        - dev: eth0
          port: 7004
      nsi:
        - name: open5gs-nrf-svc-pool
        #- addr: ::1
          port: 7777
          s_nssai:
            sst: 1
            sd: 000001

    nrf:
        sbi:
          - name: open5gs-nrf-svc-pool
            port: 7777
