apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-nssf-config
  namespace: nextepc
  labels:
    ngc-mode: nssf
    app: vcore
data:
  nssf.yaml: |
    logger:
      level: trace
      file: /opt/open5gs/nssf.log
    nssf:
      sbi:
        - dev: eth0
          port: 7004
      nsi:
        - name: open5gs-nrf-svc-pool
        #- addr: ::1
          port: 7777
          s_nssai:
            sst: 1
            sd: 000001

    nrf:
        sbi:
          - name: open5gs-nrf-svc-pool
            port: 7777
