apiVersion: v1
kind: Service
metadata:
  name: open5gs-nssf-svc-pool
  namespace: nextepc
  labels:
    ngc-mode: nssf
    app: vcore
spec:
  type: ClusterIP
  #clusterIP: None
  ports:
  - name: sbi
    port: 7004
    protocol: TCP

  publishNotReadyAddresses: true
  selector:
    ngc-mode: nssf
