apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: standard
  name: mongo-persistent-storage
  namespace: smallcell-p5g
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  nfs:
    path: /home/nfs/mongo-persistent-storage
    server: 10.177.55.101
  persistentVolumeReclaimPolicy: Retain
  #storageClassName: nfs-standard
  volumeMode: Filesystem
