apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-amf-config
  namespace: nextepc
  labels:
    ngc-mode: amf
    app: vcore
data:
  amf.yaml: |
    logger:
      level: trace
      file: /opt/open5gs/amf.log
    amf:
      sbi:
        - dev: eth0
          port: 7001
      ngap:
        - dev: eth0
      guami:
        - plmn_id:
            mcc: "999"
            mnc: "70"
          amf_id:
            region: 1
            set: 1
      tai:
        - plmn_id:
            mcc: "999"
            mnc: "70"
          tac: 0001 #[1, 2, 3]
      plmn_support:
        - plmn_id:
            mcc: "999"
            mnc: "70"
          s_nssai:
           - sst: 1
             sd: 000001
      security:
          integrity_order : [ NIA2, NIA1, NIA0 ]
          ciphering_order : [ NEA2, NEA1, NEA0 ]
      network_name:
          full: Open5GS
      amf_name: open5gs-amf0

    nrf:
        sbi:
          - name: open5gs-nrf-svc-pool
            port: 7777
