apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-udm-config
  namespace: nextepc
  labels:
    ngc-mode: udm
    app: vcore
data:
  udm.yaml: |
    logger:
      level: trace
      file: /opt/open5gs/udm.log
    udm:
      sbi:
        - dev: eth0
          port: 7007

    nrf:
        sbi:
          - name: open5gs-nrf-svc-pool
            port: 7777
