apiVersion: v1
kind: Service
metadata:
  name: open5gs-udm-svc-pool
  namespace: nextepc
  labels:
    ngc-mode: udm
    app: vcore
spec:
  type: ClusterIP
  #clusterIP: None
  ports:
  - name: sbi
    port: 7007
    protocol: TCP

  publishNotReadyAddresses: true
  selector:
    ngc-mode: udm
