apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-udm-config
  namespace: smallcell-p5g
  labels:
    ngc-mode: udm
data:
  udm.yaml: |
    logger:
      level: trace

    udm:
      sbi:
        - dev: eth0
          port: 7007

    nrf:
        sbi:
          - name: open5gs-nrf-svc-pool
            port: 7777
