apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-pcf-config
  namespace: smallcell-p5g
  labels:
    ngc-mode: pcf
data:
  pcf.yaml: |
    logger:
      level: trace

    pcf:
      sbi:
        - dev: eth0
          port: 7005

    nrf:
        sbi:
          - name: open5gs-nrf-svc-pool
            port: 7777
