apiVersion: apps/v1
kind: StatefulSet 
metadata:
  name: open5gs-pcf
  namespace: nextepc
  labels:
    ngc-mode: pcf
    app: vcore
spec:
  replicas: 1
  serviceName: "open5gs-pcf-svc-pool"
  selector:
    matchLabels:
      ngc-mode: pcf
  template:
    metadata:          
      labels:
        ngc-mode: pcf
    spec:
      containers:
        - name: pcf
          image: kikikiky/open5gs:2.0.0
          imagePullPolicy: Always
          env:
            - name: DB_URI
              value: "mongodb://mongo/open5gs?replicaSet=rs0"
          command: ["/bin/sh", "-c"]
          args:
            - echo "Wait. for DNS";
              sleep 20;
              open5gs-pcfd -c /opt/open5gs/etc/open5gs/pcf.yaml;
          ports:
            - name: sbi
              containerPort: 7005
              protocol: TCP
          volumeMounts:
          - name: open5gs-pcf-config
            mountPath: /opt/open5gs/etc/open5gs/pcf.yaml
            subPath: "pcf.yaml"
      volumes:
        - name: open5gs-pcf-config
          configMap:
            name: open5gs-pcf-config
