apiVersion: v1
kind: Service
metadata:
  name: open5gs-ausf-svc-pool
  namespace: smallcell-p5g
  labels:
    ngc-mode: ausf
spec:
  type: ClusterIP
  #clusterIP: None
  ports:
  - name: sbi
    port: 7002
    protocol: TCP

  publishNotReadyAddresses: true
  selector:
    ngc-mode: ausf
