apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-ausf-config
  namespace: smallcell-p5g
  labels:
    ngc-mode: ausf
data:
  ausf.yaml: |
    logger:
      level: trace

    ausf:
      sbi:
        - dev: eth0
          port: 7002

    nrf:
        sbi:
          - name: open5gs-nrf-svc-pool
            port: 7777
