apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-ausf-config
  namespace: nextepc
  labels:
    ngc-mode: ausf
    app: vcore
data:
  ausf.yaml: |
    logger:
      level: trace
      file: /opt/open5gs/ausf.log
    ausf:
      sbi:
        - dev: eth0
          port: 7002

    nrf:
        sbi:
          - name: open5gs-nrf-svc-pool
            port: 7777
