apiVersion: v1
kind: Service
metadata:
  name: open5gs-bsf-svc-pool
  namespace: yo-p5g
  labels:
    ngc-mode: bsf
spec:
  type: ClusterIP
  #clusterIP: None
  ports:
  - name: sbi
    port: 7003
    protocol: TCP

  publishNotReadyAddresses: true
  selector:
    ngc-mode: bsf
