apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-bsf-config
  namespace: nextepc
  labels:
    ngc-mode: bsf
    app: vcore
data:
  bsf.yaml: |
    logger:
      level: trace
      file: /opt/open5gs/bsf.log
    bsf:
      sbi:
        - dev: eth0
          port: 7003

    nrf:
        sbi:
          - name: open5gs-nrf-svc-pool
            port: 7777
