apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-upf-config
  namespace: nextepc
  labels:
    ngc-mode: upf
    app: vcore
data:
  upf.yaml: |
    logger:
      level: trace
      file: /opt/open5gs/upf.log
    upf:
        pfcp:
          dev: eth0
        gtpu:
          dev: eth0
          advertise: 10.177.55.104
        subnet:
          - addr: 100.45.0.1/16
            dnn: internet.lgep5g.net
            dev: ogstun
    smf:
        pfcp:
          #- addr: 10.96.100.104
          - name: open5gs-smf-svc-pool

  entrypoint.sh: |
    #!/bin/bash

    set -eo pipefail

    # tun iface create
    #function tun_create {
         ###########################################################################
        if ! grep "ogstun" /proc/net/dev > /dev/null; then
            echo "Creating ogstun device"
            ip tuntap add name ogstun mode tun
        fi

        ip addr del $IPV4_TUN_ADDR dev ogstun 2> /dev/null || true
        ip addr add $IPV4_TUN_ADDR dev ogstun;

        sysctl -w net.ipv6.conf.all.disable_ipv6=0;         
        ip addr del $IPV6_TUN_ADDR dev ogstun 2> /dev/null || true
        ip addr add $IPV6_TUN_ADDR dev ogstun
    
        ip link set ogstun up
        sh -c "echo 1 > /proc/sys/net/ipv4/ip_forward";
        if [ "$ENABLE_NAT" = true ] ; then
          iptables -t nat -A POSTROUTING -s $IPV4_TUN_SUBNET ! -o ogstun -j MASQUERADE;
        fi

        ###############################################################################
        #}

    #iptables -t nat -A POSTROUTING -o net1 -j MASQUERADE

        $@

    exit 1
