apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-nrf-config
  namespace: smallcell-p5g
  labels:
    ngc-mode: nrf
data:
  nrf.yaml: |
    logger:
      level: trace

    nrf:
        sbi:
          - dev: eth0
            port: 7777
