apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-nrf-config
  namespace: nextepc
  labels:
    ngc-mode: nrf
    app: vcore
data:
  nrf.yaml: |
    logger:
      level: trace
      file: /opt/open5gs/nrf.log
    nrf:
        sbi:
          - dev: eth0
            port: 7777
