apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: open5gs-nrf
  namespace: nextepc
  labels:
    ngc-mode: nrf
    app: vcore
spec:
  replicas: 1
  serviceName: "open5gs-nrf-svc-pool"
  selector:
    matchLabels:
      ngc-mode: nrf
  template:
    metadata:
      labels:
       ngc-mode: nrf
    spec:   
      containers:
        - name: nrf
          image: kikikiky/open5gs:2.0.0
          imagePullPolicy: Always          
          command: ["/bin/sh", "-c"]
          args:
            - echo "Wait. for DNS";
              sleep 20;
              open5gs-nrfd -c /opt/open5gs/etc/open5gs/nrf.yaml;
          ports:
            - name: sbi
              containerPort: 7777
              protocol: TCP
          volumeMounts:
            - name: open5gs-nrf-config
              mountPath: /opt/open5gs/etc/open5gs/nrf.yaml
              subPath: "nrf.yaml"
      volumes:
        - name: open5gs-nrf-config
          configMap:
            name: open5gs-nrf-config
