apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-udr-config
  namespace: nextepc
  labels:
    ngc-mode: udr
    app: vcore
data:
  udr.yaml: |
    logger:
      level: trace
      file: /opt/open5gs/udr.log
    udr:
      sbi:
        - dev: eth0
          port: 7008

    nrf:
        sbi:
          - name: open5gs-nrf-svc-pool
            port: 7777
